<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Pantai;

class PantaiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dataPantai = [
            [
                'nama' => 'Pantai Parangtritis',
                'gambar' => 'parangtritis.jpeg',
                'lokasi' => 'Bantul',
                'deskripsi' => 'Pantai legendaris dengan pasir hitam dan legenda Nyi Roro Kidul.',
                'harga_tiket' => 10000,
                'keindahan' => 4,
                'aksesibilitas' => 5,
                'fasilitas' => 4,
                'aktivitas' => 3,
            ],
            [
                'nama' => 'Pantai Indrayanti',
                'gambar' => 'indrayanti.jpeg',
                'lokasi' => 'Gunungkidul',
                'deskripsi' => 'Pantai pasir putih dengan kafe dan penginapan di sekitarnya.',
                'harga_tiket' => 15000,
                'keindahan' => 5,
                'aksesibilitas' => 4,
                'fasilitas' => 5,
                'aktivitas' => 4,
            ],
            [
                'nama' => 'Pantai Drini',
                'gambar' => 'drini.jpeg',
                'lokasi' => 'Gunungkidul',
                'deskripsi' => 'Pantai dengan pulau karang kecil dan air jernih.',
                'harga_tiket' => 10000,
                'keindahan' => 4,
                'aksesibilitas' => 4,
                'fasilitas' => 4,
                'aktivitas' => 3,
            ],
                        [
                'nama' => 'Pantai Krakal',
                'gambar' => 'krakal.jpeg',
                'lokasi' => 'Gunungkidul',
                'deskripsi' => 'Pantai dengan ombak tinggi dan pasir putih.',
                'harga_tiket' => 10000,
                'keindahan' => 4,
                'aksesibilitas' => 3,
                'fasilitas' => 3,
                'aktivitas' => 4,
            ],
            [
                'nama' => 'Pantai Kukup',
                'gambar' => 'kukup.jpeg',
                'lokasi' => 'Gunungkidul',
                'deskripsi' => 'Pantai kecil dengan batu karang besar dan jembatan.',
                'harga_tiket' => 10000,
                'keindahan' => 4,
                'aksesibilitas' => 3,
                'fasilitas' => 4,
                'aktivitas' => 2,
            ],
            [
                'nama' => 'Pantai Ngobaran',
                'gambar' => 'ngobaran.jpeg',
                'lokasi' => 'Gunungkidul',
                'deskripsi' => 'Pantai unik dengan nuansa budaya Hindu dan tebing.',
                'harga_tiket' => 10000,
                'keindahan' => 5,
                'aksesibilitas' => 3,
                'fasilitas' => 3,
                'aktivitas' => 2,
            ],
            [
                'nama' => 'Pantai Wediombo',
                'gambar' => 'wediombo.jpeg',
                'lokasi' => 'Gunungkidul',
                'deskripsi' => 'Pantai luas dengan batu karang dan tempat snorkeling.',
                'harga_tiket' => 10000,
                'keindahan' => 4,
                'aksesibilitas' => 3,
                'fasilitas' => 4,
                'aktivitas' => 4,
            ],
            [
                'nama' => 'Pantai Baron',
                'gambar' => 'baron.jpeg',
                'lokasi' => 'Gunungkidul',
                'deskripsi' => 'Pantai dengan muara sungai dan tempat pelelangan ikan.',
                'harga_tiket' => 10000,
                'keindahan' => 3,
                'aksesibilitas' => 4,
                'fasilitas' => 4,
                'aktivitas' => 3,
            ],
            [
                'nama' => 'Pantai Pok Tunggal',
                'gambar' => 'poktunggal.jpeg',
                'lokasi' => 'Gunungkidul',
                'deskripsi' => 'Pantai dengan pohon ikonik dan tebing indah.',
                'harga_tiket' => 10000,
                'keindahan' => 5,
                'aksesibilitas' => 2,
                'fasilitas' => 3,
                'aktivitas' => 3,
            ],
            [
                'nama' => 'Pantai Jogan',
                'gambar' => 'jogan.jpeg',
                'lokasi' => 'Gunungkidul',
                'deskripsi' => 'Pantai dengan air terjun langsung ke laut.',
                'harga_tiket' => 10000,
                'keindahan' => 5,
                'aksesibilitas' => 2,
                'fasilitas' => 2,
                'aktivitas' => 3,
            ],
            [
                'nama' => 'Pantai Siung',
                'gambar' => 'siung.jpeg',
                'lokasi' => 'Gunungkidul',
                'deskripsi' => 'Pantai tenang dengan tebing untuk panjat tebing.',
                'harga_tiket' => 10000,
                'keindahan' => 4,
                'aksesibilitas' => 2,
                'fasilitas' => 3,
                'aktivitas' => 5,
            ],
            [
                'nama' => 'Pantai Nglambor',
                'gambar' => 'nglambor.jpeg',
                'lokasi' => 'Gunungkidul',
                'deskripsi' => 'Pantai cocok untuk snorkeling dengan air jernih.',
                'harga_tiket' => 10000,
                'keindahan' => 4,
                'aksesibilitas' => 2,
                'fasilitas' => 3,
                'aktivitas' => 5,
            ],
            [
                'nama' => 'Pantai Timang',
                'gambar' => 'timang.jpeg',
                'lokasi' => 'Gunungkidul',
                'deskripsi' => 'Pantai terkenal dengan gondola manual ke batu karang.',
                'harga_tiket' => 15000,
                'keindahan' => 4,
                'aksesibilitas' => 2,
                'fasilitas' => 2,
                'aktivitas' => 5,
            ],
            [
                'nama' => 'Pantai Sundak',
                'gambar' => 'sundak.jpeg',
                'lokasi' => 'Gunungkidul',
                'deskripsi' => 'Pantai bersih, cocok untuk keluarga.',
                'harga_tiket' => 10000,
                'keindahan' => 4,
                'aksesibilitas' => 4,
                'fasilitas' => 4,
                'aktivitas' => 3,
            ],
            [
                'nama' => 'Pantai Seruni',
                'gambar' => 'seruni.jpeg',
                'lokasi' => 'Gunungkidul',
                'deskripsi' => 'Pantai tersembunyi dengan tebing karang tinggi.',
                'harga_tiket' => 10000,
                'keindahan' => 4,
                'aksesibilitas' => 2,
                'fasilitas' => 2,
                'aktivitas' => 2,
            ],
            [
                'nama' => 'Pantai Ngrenehan',
                'gambar' => 'ngrenehan.jpeg',
                'lokasi' => 'Gunungkidul',
                'deskripsi' => 'Pantai nelayan dengan panorama teluk kecil.',
                'harga_tiket' => 10000,
                'keindahan' => 3,
                'aksesibilitas' => 3,
                'fasilitas' => 3,
                'aktivitas' => 2,
            ],
            [
                'nama' => 'Pantai Nguyahan',
                'gambar' => 'nguyahan.jpg',
                'lokasi' => 'Gunungkidul',
                'deskripsi' => 'Pantai tenang dengan pasir putih dan sedikit pengunjung.',
                'harga_tiket' => 10000,
                'keindahan' => 4,
                'aksesibilitas' => 3,
                'fasilitas' => 2,
                'aktivitas' => 2,
            ],
            [
                'nama' => 'Pantai Gesing',
                'gambar' => 'gesing.jpeg',
                'lokasi' => 'Gunungkidul',
                'deskripsi' => 'Pantai nelayan dengan tebing tinggi di kanan kiri.',
                'harga_tiket' => 10000,
                'keindahan' => 3,
                'aksesibilitas' => 3,
                'fasilitas' => 3,
                'aktivitas' => 3,
            ],
            [
                'nama' => 'Pantai Greweng',
                'gambar' => 'greweng.jpeg',
                'lokasi' => 'Gunungkidul',
                'deskripsi' => 'Pantai tersembunyi di balik bukit, cocok untuk berkemah.',
                'harga_tiket' => 5000,
                'keindahan' => 4,
                'aksesibilitas' => 1,
                'fasilitas' => 1,
                'aktivitas' => 4,
            ],
            [
                'nama' => 'Pantai Jungwok',
                'gambar' => 'jungwok.jpeg',
                'lokasi' => 'Gunungkidul',
                'deskripsi' => 'Pantai sunyi dengan formasi batu unik.',
                'harga_tiket' => 5000,
                'keindahan' => 4,
                'aksesibilitas' => 2,
                'fasilitas' => 2,
                'aktivitas' => 3,
            ],
            [
                'nama' => 'Pantai Sadeng',
                'gambar' => 'sadeng.jpeg',
                'lokasi' => 'Gunungkidul',
                'deskripsi' => 'Pelabuhan nelayan modern dengan pemandangan laut.',
                'harga_tiket' => 10000,
                'keindahan' => 3,
                'aksesibilitas' => 4,
                'fasilitas' => 3,
                'aktivitas' => 2,
            ],
                        [
                'nama' => 'Pantai Glagah',
                'gambar' => 'glagah.jpeg',
                'lokasi' => 'Kulon Progo',
                'deskripsi' => 'Pantai dengan pemecah ombak beton dan dermaga.',
                'harga_tiket' => 10000,
                'keindahan' => 3,
                'aksesibilitas' => 4,
                'fasilitas' => 3,
                'aktivitas' => 2,
            ],
            [
                'nama' => 'Pantai Trisik',
                'gambar' => 'trisik.jpeg',
                'lokasi' => 'Kulon Progo',
                'deskripsi' => 'Pantai dengan konservasi penyu dan hamparan luas.',
                'harga_tiket' => 10000,
                'keindahan' => 3,
                'aksesibilitas' => 3,
                'fasilitas' => 3,
                'aktivitas' => 2,
            ],
            [
                'nama' => 'Pantai Kuwaru',
                'gambar' => 'kuwaru.jpeg',
                'lokasi' => 'Bantul',
                'deskripsi' => 'Pantai rindang dengan pohon cemara dan kuliner laut.',
                'harga_tiket' => 10000,
                'keindahan' => 3,
                'aksesibilitas' => 5,
                'fasilitas' => 4,
                'aktivitas' => 3,
            ],
            [
                'nama' => 'Pantai Samas',
                'gambar' => 'samas.jpg',
                'lokasi' => 'Bantul',
                'deskripsi' => 'Pantai luas dengan mercusuar dan kawasan pertanian laut.',
                'harga_tiket' => 10000,
                'keindahan' => 3,
                'aksesibilitas' => 4,
                'fasilitas' => 3,
                'aktivitas' => 2,
            ],
            
        ];

        foreach ($dataPantai as $pantai) {
            Pantai::create($pantai);
        }
    }
}
